vanish-on-all-menu-names: true #self-explained
# TODO items-return-delay: 1
menu-names: [] #menu where hide items
blacklist-menu-names: [] #real blacklist. works everywhere
# TODO give-gathered-items: true #should be gathered items in vanish be in inventory later